# -*- coding: utf-8 -*-
"""Copy of classic_pcod.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LPEVinO3pHKP_zELPwjsUfeVXQ6gBUzy
"""

!pip install xgboost lightgbm catboost imbalanced-learn tensorflow

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# ML Models
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier

# Preprocessing
from sklearn.model_selection import train_test_split, StratifiedKFold, GridSearchCV
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, roc_curve, auc, f1_score, precision_score, recall_score
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# Imbalanced data handling
from imblearn.over_sampling import SMOTE

# Deep learning for temporal modeling
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout, Attention

# Ensemble
from sklearn.ensemble import VotingClassifier

# Misc
import warnings
warnings.filterwarnings('ignore')

# Load dataset
df = pd.read_csv('pcos_flare_synthetic_dataset.csv')

# Preview
print(df.head())
print(df['flare_label'].value_counts(normalize=True))

# Check missing values
print(df.isnull().sum())

# Separate features and target
target = 'flare_label'
X = df.drop(columns=[target, 'user_id', 'date'])
y = df[target]

# Identify categorical and numerical features
categorical_cols = X.select_dtypes(include=['object']).columns.tolist()  # e.g. flow_intensity, pain_level, ovulation_signs, stressor_notes
numerical_cols = X.select_dtypes(include=[np.number]).columns.tolist()

# Preprocessor pipeline
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numerical_cols),
        ('cat', OneHotEncoder(drop='first'), categorical_cols)
    ]
)

# Transform features
X_processed = preprocessor.fit_transform(X)

# Apply SMOTE on training data only---------- this is so we can have equal class
X_train, X_test, y_train, y_test = train_test_split(
    X_processed, y, test_size=0.2, random_state=42, stratify=y
)

smote = SMOTE(random_state=42)
X_train_res, y_train_res = smote.fit_resample(X_train, y_train)

print(f"Before SMOTE: {np.bincount(y_train)}")
print(f"After SMOTE: {np.bincount(y_train_res)}")

"""Used RandomizedSearchCV for XGBoost, GridSearchCV for LightGBM, and Bayesian optimization for CatBoost. Parameters like learning rate, tree depth, and number of estimators were tuned to maximize F1-score."""

from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier

from sklearn.model_selection import RandomizedSearchCV

xgb = XGBClassifier(use_label_encoder=False, eval_metric='logloss', random_state=42)

param_dist_xgb = {
    'n_estimators': [50, 100, 200],
    'max_depth': [3, 5, 7],
    'learning_rate': [0.01, 0.05, 0.1],
    'subsample': [0.7, 1.0],
    'colsample_bytree': [0.7, 1.0]
}

random_search_xgb = RandomizedSearchCV(xgb, param_distributions=param_dist_xgb, n_iter=10, cv=3, scoring='f1', n_jobs=-1, random_state=42)
random_search_xgb.fit(X_train_res, y_train_res)

print("XGBoost best parameters:", random_search_xgb.best_params_)
best_xgb_model = random_search_xgb.best_estimator_

from sklearn.model_selection import GridSearchCV

lgbm = LGBMClassifier(random_state=42)

param_grid_lgbm = {
    'n_estimators': [50, 100, 200],
    'num_leaves': [31, 50, 70],
    'learning_rate': [0.01, 0.05, 0.1],
    'subsample': [0.7, 1.0],
    'colsample_bytree': [0.7, 1.0]
}

grid_search_lgbm = GridSearchCV(lgbm, param_grid_lgbm, cv=3, scoring='f1', n_jobs=-1)
grid_search_lgbm.fit(X_train_res, y_train_res)

print("LightGBM best parameters:", grid_search_lgbm.best_params_)
best_lgbm_model = grid_search_lgbm.best_estimator_

!pip install scikit-optimize

from skopt import BayesSearchCV
from catboost import CatBoostClassifier

cat = CatBoostClassifier(random_state=42, verbose=0)

param_space_cat = {
    'iterations': (100, 500),
    'depth': (4, 10),
    'learning_rate': (0.01, 0.3, 'log-uniform'),
    'l2_leaf_reg': (1, 10)
}

opt_cat = BayesSearchCV(cat, param_space_cat, cv=3, scoring='f1', n_jobs=-1, n_iter=25, random_state=42)
opt_cat.fit(X_train_res, y_train_res)

print("CatBoost best parameters:", opt_cat.best_params_)
best_cat_model = opt_cat.best_estimator_

"""Stratified k-fold cross-validation was applied, focusing on F1-score to balance precision and recall, crucial for sensitive health predictions.


"""

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

models = {
    'XGBoost': XGBClassifier(**random_search_xgb.best_params_, use_label_encoder=False, eval_metric='logloss', random_state=42),
    'LightGBM': LGBMClassifier(random_state=42),
    'CatBoost': CatBoostClassifier(random_state=42, verbose=0)
}

for name, model in models.items():
    f1_scores = []
    for train_idx, val_idx in skf.split(X_train_res, y_train_res):
        X_tr, X_val = X_train_res[train_idx], X_train_res[val_idx]
        y_tr, y_val = y_train_res[train_idx], y_train_res[val_idx]

        if name == 'CatBoost':
            model.fit(X_tr, y_tr, eval_set=(X_val, y_val), early_stopping_rounds=30)
        else:
            model.fit(X_tr, y_tr)

        y_pred = model.predict(X_val)
        score = f1_score(y_val, y_pred)
        f1_scores.append(score)

    print(f"{name} average F1 score (CV): {np.mean(f1_scores):.4f}")

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix

model_preds = {
    'XGBoost': best_xgb_model.predict(X_test),
    'LightGBM': best_lgbm_model.predict(X_test),
    'CatBoost': best_cat_model.predict(X_test)
}

plt.figure(figsize=(18, 5))

for i, (model_name, y_pred) in enumerate(model_preds.items()):
    cm = confusion_matrix(y_test, y_pred)
    plt.subplot(1, 3, i+1)
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=False)
    plt.title(f'{model_name} Confusion Matrix')
    plt.xlabel('Predicted Label')
    plt.ylabel('True Label')

plt.tight_layout()
plt.show()

"""lstm model hybrid"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler, LabelEncoder
from sklearn.model_selection import train_test_split

# Load dataset
df = pd.read_csv('pcos_flare_synthetic_dataset.csv')
df['date'] = pd.to_datetime(df['date'])
df = df.sort_values(['user_id', 'date'])

# ----- Static Features ---------
static_features = ['age']  # Expand if more static info (BMI, smoking, alcohol) is available

# ----- Temporal Features -------
temporal_features = [
    'acne_severity', 'hirsutism_severity', 'mood_severity', 'energy_severity', 'cravings_severity',
    'cycle_day', 'flow_intensity', 'pain_level', 'ovulation_signs',
    'sleep_quality_score', 'sleep_duration', 'stress_score', 'food_GI', 'food_GL',
    'fasting_glucose', 'weight', 'cycle_length', 'hrv'
]
categorical_temporal = ['flow_intensity', 'pain_level', 'ovulation_signs']

# Encode categorical temporal features
for col in categorical_temporal:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col].astype(str))

# Fill missing values within each user time series
df = df.groupby('user_id').apply(lambda group: group.fillna(method='ffill').fillna(method='bfill'))
df.reset_index(drop=True, inplace=True)

# Normalize temporal features
scaler = MinMaxScaler()
df[temporal_features] = scaler.fit_transform(df[temporal_features].values)

# ----- Aggregate and Sequence Creation -----
SEQUENCE_LENGTH = 7

def create_sequences(df, user_col, static_features, temporal_features, target_col, seq_len=SEQUENCE_LENGTH):
    sequences, static_data, labels = [], [], []
    for user in df[user_col].unique():
        user_df = df[df[user_col] == user]
        user_static = user_df.iloc[0][static_features].values  # Static for user
        temp_feats = user_df[temporal_features].values
        targets = user_df[target_col].values
        for i in range(len(user_df) - seq_len):
            sequences.append(temp_feats[i:i+seq_len])
            static_data.append(user_static)
            labels.append(targets[i+seq_len])
    return np.array(static_data), np.array(sequences), np.array(labels)

static_X, seq_X, y = create_sequences(
    df, 'user_id', static_features, temporal_features, 'flare_label', SEQUENCE_LENGTH
)

print(f'Static feature shape: {static_X.shape}')
print(f'Sequence data shape: {seq_X.shape}')
print(f'Labels shape: {y.shape}')

# Split for train/test
X_static_train, X_static_test, X_seq_train, X_seq_test, y_train, y_test = train_test_split(
    static_X, seq_X, y, test_size=0.2, random_state=42, stratify=y
)

!pip install tensorflow

import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, LSTM, Dense, Dropout, Concatenate
from tensorflow.keras.callbacks import EarlyStopping

# Define input shapes
SEQ_LEN = X_seq_train.shape[1]
N_TEMPORAL = X_seq_train.shape[2]
N_STATIC = X_static_train.shape[1]

# Sequential input (time series window)
seq_input = Input(shape=(SEQ_LEN, N_TEMPORAL), name='sequence_input')
x = LSTM(64)(seq_input)
x = Dropout(0.3)(x)

# Static demographic input (e.g., age)
static_input = Input(shape=(N_STATIC,), name='static_input')
s = Dense(8, activation='relu')(static_input)

# Merge static and sequence features
merged = Concatenate()([x, s])
output = Dense(1, activation='sigmoid')(merged)

model = Model(inputs=[seq_input, static_input], outputs=output)
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

early_stop = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

# Train the model
history = model.fit(
    [X_seq_train, X_static_train], y_train,
    epochs=40,
    batch_size=32,
    validation_split=0.1,
    callbacks=[early_stop],
    verbose=2
)

# Evaluate
loss, accuracy = model.evaluate([X_seq_test, X_static_test], y_test, verbose=0)
print(f"LSTM+Static Test Accuracy: {accuracy:.4f}")

"""gru hybrid"""

from tensorflow.keras.layers import GRU

# --- GRU sequence model with static features integration ---

# Sequential Input
seq_input = Input(shape=(SEQ_LEN, N_TEMPORAL), name='sequence_input')
x = GRU(64)(seq_input)
x = Dropout(0.3)(x)

# Static Input
static_input = Input(shape=(N_STATIC,), name='static_input')
s = Dense(8, activation='relu')(static_input)

# Merge and Output
merged = Concatenate()([x, s])
output = Dense(1, activation='sigmoid')(merged)

model_gru = Model(inputs=[seq_input, static_input], outputs=output)
model_gru.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

early_stop = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

history_gru = model_gru.fit(
    [X_seq_train, X_static_train], y_train,
    epochs=40, batch_size=32, validation_split=0.1,
    callbacks=[early_stop], verbose=2
)

loss, accuracy = model_gru.evaluate([X_seq_test, X_static_test], y_test, verbose=0)
print(f"GRU+Static Test Accuracy: {accuracy:.4f}")